"""Train YOLOv11 segmentation model on FoodSeg103.

Usage:
    python train_food.py

The script loads food.yaml (generated by convert_foodseg103.py) and trains
a yolo11n-seg model. On RTX 4050 (6GB VRAM) use batch=8; reduce to batch=4 if OOM.
On cloud GPUs (RTX 4090, A100) increase batch to 16 or 32.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
FOOD_YAML = SCRIPT_DIR / "food.yaml"
PROJECT_DIR = SCRIPT_DIR / "runs"
BASE_MODEL = SCRIPT_DIR / "yolo11n-seg.pt"

# GPU tier detection: adjust batch size based on available VRAM
BATCH_SIZE = int(os.environ.get("BATCH_SIZE", "8"))
IMGSZ = int(os.environ.get("IMGSZ", "640"))
EPOCHS = int(os.environ.get("EPOCHS", "100"))


def main():
    if not FOOD_YAML.exists():
        print(f"错误: {FOOD_YAML} 不存在")
        print("请先运行: python convert_foodseg103.py")
        sys.exit(1)

    if not BASE_MODEL.exists():
        print(f"错误: 基础模型 {BASE_MODEL} 不存在")
        print("请将 yolo11n-seg.pt 上传到该目录，或设置 BASE_MODEL 环境变量")
        sys.exit(1)

    from ultralytics import YOLO

    model = YOLO(str(BASE_MODEL))

    print(f"训练配置:")
    print(f"  数据集: {FOOD_YAML}")
    print(f"  Epochs: {EPOCHS}")
    print(f"  Batch: {BATCH_SIZE}")
    print(f"  Image size: {IMGSZ}")
    print(f"  输出目录: {PROJECT_DIR}")
    print()

    results = model.train(
        data=str(FOOD_YAML),
        epochs=EPOCHS,
        imgsz=IMGSZ,
        batch=BATCH_SIZE,
        device=0,
        patience=20,
        amp=False,
        workers=4,
        project=str(PROJECT_DIR),
        name="food_seg_v1",
        exist_ok=True,
    )

    best_pt = PROJECT_DIR / "food_seg_v1" / "weights" / "best.pt"
    print(f"\n训练完成!")
    print(f"  最佳模型: {best_pt}")
    print(f"  结果图: {PROJECT_DIR / 'food_seg_v1' / 'results.png'}")
    print(f"\n部署命令:")
    print(f"  cp {best_pt} ../../demo/models/food_seg_v1.pt")
    print(f"  export FOOD_MODEL_PATH=../../demo/models/food_seg_v1.pt")

    return results


if __name__ == "__main__":
    main()
